version: '3.3'

services:
    webapp-server:
      build:
        context: .
        dockerfile: Dockerfile
      image: myapp-server-img
      container_name: node-express
      volumes:
       - .:/usr/src/app
       - /usr/src/app/node_modules
      ports:
        - "8080:8080"
      depends_on:
        - mongo
      env_file: .env
      environment:
        - MONGO_HOSTNAME=$MONGO_HOSTNAME
        - MONGO_PORT=$MONGO_PORT
        - MONGO_DB=$MONGO_DB
    mongo:
      image: mongo
      container_name: mongodb
      ports:
        - "27017:27017"

    client:
      build:
        context: ./client
        dockerfile: Dockerfile
      image: myapp-client
      stdin_open: true
      container_name: react-client
      command: yarn start
      volumes:
        - ./client/:/usr/app
        - /usr/app/node_modules
      ports:
        - "3000:3000"
      networks:
        - app-network